dist: bionic
language: cpp
addons:
  sonarcloud:
    organization: "sebas-mora28"
      token:
        secure: "f6oB17H6CJv9XYWQBmgNM7iSOak6yI34UH3FbZBAHfS37MB9+fOWWT4fKaq2wO2KqiPjQBKS4m/UPujw4tjfMa+g1/cRzTyTfpEymg8m1zVCQcC8t01isM5fiN6pZPRScr5b9GEEjWnAmQSSxoUXQhvk58DZyWXVCEgy5d81gELYgq4+KDBOzfDBtifRb8iNgLXToPuBUt291rTfRnaZFpVgkc7Z3CMgKhgtaZrWNWrlTj+XRoEOCO0778VurZuOTGN2TjdY4yKq+juY2+B6xvVwiC11+crRxq/xApFr1v6CB7qiQJOnGQJxK+zeyTe8Tg8uWpwX0SwA2buCPxN5xtZVqsjum6vdn5AW14Ior8L+Ow6Tm/hWQFbcdGefhj5tWtRcw9r5ZTq5+zIhAPyfWJOJ1JIN5pPBTOMTkHIoVQuTXipURcyhH63P/RSqj5N8VSqf/MAq22JgehGKWhTMBtnvwcXichV1zQf5SLaE0uMPWfp6Kv2BVebNZunDYXPim2+ZfVuxLCMpf8tG/tjbjvTpmOoC38saLteZ5Q+cNenZiji5vAztEzX49BrwQGO1370V2oNfaTJvZwZaDpTjtJo0dxY4vkoo4MtC7tyLwDiX+t2DEEdxHtaEUY/RYK+JiG0UuemObQeuc+O869oJQDTcaLJje+f9cSGPz6jvRnk="

script:
  - sudo apt-get install libjsoncpp-dev
  - cd MemoryManager
  - rm -f build bw-output && mkdir build && cd build && cmake ..
  - build-wrapper-linux-x86-64 --out-dir ../bw-output make all && cd ..
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output