dist: bionic
language: cpp
addons:
  sonarcloud:
    organization: "sebas-mora28"
      token:
        secure: "IKUBYEa4yVBjChU+ldv/qkaklwXXbWonRL4GKfMbqwJcWLK+cbxCl3nPKqKv0fKd5RpYlvn6HvIJYvwf4qYLUMIqRwhgC0eYhcGqKJN7jte/unnb0rffcFLZJu998wRBodnYP9eOlYoSAPbeZb20VEHpswYGgJpcltkPfSbLz1Ynf4LfU8mup4QXhrkUbmCAjj5bnvajfu6eOjbsnGgk/q3dXrvigeJucvH32dHt/yuBmP1e8/EjVWFo9boRLsKDRXjxnV5jQaIm2wlIa1+DwYRHPWA1HllgYnNvQdQ2MtW7sdKIK32utW0ueg+Zncs6dyYpEI6kb3XzAarljCQzx6H4X+ZcHBKgLC1zdROgWzZfVgcG3g8xOF4nXJsDCcu9oxD80DMWe9QK05HcTbFayVkzupqMmTuPqtmvv3PPBpxMZCUwr482cwz37TXH5EVEc4YFt3bcsQoWQvf30b43QAA+d/mrcs64rRkAUdsiE/PKd3uqablkrQWam6A8QtydfksoPKO/XyY9zz6qA9svl7TkeTHbkggnLkdc5BbLNtNAw/SxS+qJNRWdPaW+4FiABnqPXDE14siReon9uHMvtXj/zjNeAJqPWXxytzeq62wM/UAgSjgHw33c/M57xzMqtxUmMACOWVXPq3QItZUWBQmPfxTVUfDwqb8wdTpCXSA="
script:
  - sudo apt-get install libjsoncpp-dev
  - cd MemoryManager
  - rm -f build bw-output && mkdir build && cd build && cmake ..
  - build-wrapper-linux-x86-64 --out-dir ../bw-output make all && cd ..
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output